### ISSUE TITLE
Where did the status code 599 come from, and where is it used?

### ISSUE THREAD

**Issue by citricsquid** [rmaake1/httpstatuses#22]
The status code [599](http://httpstatus.es/599) is non-standard, it doesn't exist in any RFC, but it appears to be quite widely used, it's the 10th most popular status code on the website. The description I originally used came from wikipedia, now the wikipedia page has been updated with circular references, and my google searches aren't returning much useful information on where the code came from, or who's using it... but it must be someone!

Any research / input here is greatly appreciated.

**Comment by passcod** [comment]
Wikipedia source in October 2015 was https://github.com/serrynaimo/http-status-singlish#599-network-connect-timeout-error-unknown
