### ISSUE TITLE
404 when attempting to view details about a status code!

### ISSUE THREAD

**Issue by sbrl** [rmaake1/httpstatuses#61]
I'm getting a 404 when I try to view details about any of the http statuses on https://httpstatus.es/! 

Example URL: https://httpstatuses.com/408

![image](https://cloud.githubusercontent.com/assets/9929737/20210172/f2309e6e-a7ef-11e6-8cf1-d180f8fcde4d.png)

Apparently Apache is having trouble finding a 404 error page to display too.

**Comment by anshuman73** [comment]
Hi, I just tried this out. It worked out fine for me.
Can you try again ?

**Comment by sbrl** [comment]
@anshuman73 Huh. It seems to be working for me now. That's odd! Guess it must've been a temporary thing.
