### ISSUE TITLE
Missing Status Codes

### ISSUE THREAD

**Issue by lennybacon** [rmaake1/httpstatuses#70]
There are more code that could be added...

- [103](https://web.archive.org/web/20200815085423/https://evertpot.com/http/103-early-hints)
- [306](https://web.archive.org/web/20200511214543/https://evertpot.com/http/306-switch-proxy)
- [420](https://web.archive.org/web/20200511214134/https://evertpot.com/http/420-enhance-your-calm)
- [425](https://web.archive.org/web/20200511213704/https://evertpot.com/http/425-too-early)
- [430](https://web.archive.org/web/20200511204048/https://evertpot.com/http/430-would-block)

**Comment by zoidbergwill** [comment]
Duplicate of https://github.com/rmaake1/httpstatuses/issues/71?

**Comment by lennybacon** [comment]
My browser crashed. Sorry. I'll close this one.
