### ISSUE TITLE
httpstatuses.com redirects to https://www.webfx.com/web-development/glossary/http-status-codes/ now. Did the domain expire?

### ISSUE THREAD

**Issue by mrmartineau** [rmaake1/httpstatuses#75]
Wondering why this brilliant website now redirects to an inferior website. Did the domain expire? or is the redirect intended?

**Comment by theS1LV3R** [comment]
Looks like it based on WHOIS records at least:
```
Updated Date: 2022-02-23T19:47:40Z        
Creation Date: 2012-02-23T02:47:21Z       
Registry Expiry Date: 2023-02-23T02:47:21Z
```
Guessing it lasted for 10 years and now that it expired webfx quickly snatched it

**Comment by mrmartineau** [comment]
If anyone's interested, I forked this repo and deployed it to https://httpstatuses.zander.wtf

The fork can be found at https://github.com/mrmartineau/httpstatuses

**Comment by mgernand** [comment]
There are additional forks of this repo:

[httpstatuses](https://github.com/httpstatuses/httpstatuses) by @jkulton 
- The page is [https://httpstatuses.io](https://httpstatuses.io).

Additionally I created [httpstatuscodes.io](https://github.com/fluxera/httpstatuscodes.io) 
- The page is [https://httpstatuscodes.io](https://httpstatuscodes.io).
- It provides an additional JSON endpoint.
- It is an ASP.NET Core application. 

My fork uses the same markdown files from [httpstatuses](https://github.com/httpstatuses/httpstatuses) so any changes to the status code content should be made there.

**Comment by isaacbowen** [comment]
@mrmartineau @mgernand thank you thank you thank you thank you

@rmaake1 thanks for this project :) it's a regular resource for me

**Comment by jkulton** [comment]
For anyone looking for more details on what happened to the original domain(s) see [this article](https://jkulton.com/2022/reviving-httpstatuses#what-happened).

**Comment by JamesMcGuigan** [comment]
Maybe somebody whould update the URL in the github description sidebar
